import type { Clip, Trip } from "./types";
import { OFFROAD_POIS, ROADS } from "./wheatbelt-towns";

/**
 * Seed trips and clips for the MVP.
 *
 * The audio blobs themselves are generated by `scripts/generate-seed-audio.ts`
 * (which calls z-ai-web-dev-sdk TTS) and saved to `/public/audio/*.mp3`.
 * On first app run, the app fetches those MP3s and ingests them into IndexedDB.
 * After that, the app is fully offline.
 *
 * Clip `audioId` is stable across runs and matches the filename in /public/audio.
 */

const M031_TRIP_ID = "trip-m031-york-to-katanning";

const M031_TRIP: Trip = {
  id: M031_TRIP_ID,
  name: "Great Southern Hwy — York to Katanning",
  description: "M031 corridor · ~270 km · 7 towns + 2 off-road POIs",
  roadIds: ["M031"],
  accent: "#d97706",
  // Set explicitly so this sorts first (newer) in getAllTrips which orders by updatedAt desc
  updatedAt: Date.now(),
  downloaded: false,
};

const M031_CLIPS: Clip[] = [
  // --- Town clips: geofence triggers (300m radius) --------------------------
  // All town clips use geofence triggers — works regardless of whether the
  // town sits directly on M031 or on a spur road (Beverley is 17km off M031).
  // Direction filter is unset — fires when driving through in either direction.
  ...ROADS.M031.towns.map((town, idx): Clip => ({
    id: `clip-m031-${town.name.toLowerCase().replace(/\s+/g, "-")}`,
    tripId: M031_TRIP_ID,
    title: town.name,
    subtitle: `Town · ${town.lat.toFixed(4)}°, ${town.lon.toFixed(4)}°`,
    script: town.blurb ?? `${town.name} — no script available yet.`,
    trigger: {
      type: "geofence",
      lat: town.lat,
      lon: town.lon,
      radiusM: 300,
    },
    audioReady: false,
    order: idx,
  })),
  // --- Off-road POI clips: geofence triggers --------------------------------
  ...OFFROAD_POIS.map((poi, idx): Clip => ({
    id: `clip-poi-${poi.name.toLowerCase().replace(/\s+/g, "-")}`,
    tripId: M031_TRIP_ID,
    title: poi.name,
    subtitle: `POI · ${poi.radiusM} m radius`,
    script: poi.blurb,
    trigger: {
      type: "geofence",
      lat: poi.lat,
      lon: poi.lon,
      radiusM: poi.radiusM,
    },
    audioReady: false,
    // Off-road POIs sort after town clips
    order: 100 + idx,
  })),
];

/**
 * Second placeholder trip — empty but demonstrates multi-trip switching.
 * Will be populated with real content once the user specifies their route.
 */
const FUTURE_TRIP: Trip = {
  id: "trip-placeholder-future",
  name: "Your Next Trip (placeholder)",
  description: "Add your actual route here — architecture is ready",
  roadIds: [],
  accent: "#0ea5e9",
  // Set 1 second older than M031 trip so it sorts second
  updatedAt: Date.now() - 1000,
  downloaded: false,
};

export const SEED_TRIPS: Trip[] = [M031_TRIP, FUTURE_TRIP];
export const SEED_CLIPS: Clip[] = [...M031_CLIPS];

/** Map of clipId → expected audio filename in /public/audio/. */
export const SEED_AUDIO_FILES: Record<string, string> = Object.fromEntries(
  M031_CLIPS.map((clip) => [clip.id, `${clip.id}.wav`]),
);
